networks:
  db: {external: true}
services:
  micro_elmodifferencepredict:
    build: python
    container_name: micro_elmodifferencepredict
    entrypoint: python3 -c 'from language.transformer.ElmoDifferencePredict import
      ElmoDifferencePredict; from wsgiref import simple_server; simple_server.make_server("0.0.0.0",
      7777, ElmoDifferencePredict.application).serve_forever()'
    environment: {GDB_HOST: gdb, GDB_PASSWORD: '${GDB_PASSWORD}', INSIDE: 'true',
      LANG: en_US.UTF - 8, LANGUAGE: en_US.UTF-8, LC_ALL: en_US.UTF-8}
    image: full_python
    networks: [db]
    restart: unless-stopped
    volumes: [$CWD/python:/home/finn/Programming/self-reading-library/python]
  micro_layout2readingorder:
    build: python
    container_name: micro_layout2readingorder
    entrypoint: python3 -c 'from layout.Layout2ReadingOrder import Layout2ReadingOrder;
      from wsgiref import simple_server; simple_server.make_server("0.0.0.0", 7777,
      Layout2ReadingOrder.application).serve_forever()'
    environment: {GDB_HOST: gdb, GDB_PASSWORD: '${GDB_PASSWORD}', INSIDE: 'true',
      LANG: en_US.UTF - 8, LANGUAGE: en_US.UTF-8, LC_ALL: en_US.UTF-8}
    image: full_python
    networks: [db]
    restart: unless-stopped
    volumes: [$CWD/python:/home/finn/Programming/self-reading-library/python]
  micro_topicmaker:
    build: python
    container_name: micro_topicmaker
    entrypoint: python3 -c 'from topics.TopicMaker import TopicMaker; from wsgiref
      import simple_server; simple_server.make_server("0.0.0.0", 7777, TopicMaker.application).serve_forever()'
    environment: {GDB_HOST: gdb, GDB_PASSWORD: '${GDB_PASSWORD}', INSIDE: 'true',
      LANG: en_US.UTF - 8, LANGUAGE: en_US.UTF-8, LC_ALL: en_US.UTF-8}
    image: full_python
    networks: [db]
    restart: unless-stopped
    volumes: [$CWD/python:/home/finn/Programming/self-reading-library/python]
  micro_txt2mp3:
    build: python
    container_name: micro_txt2mp3
    entrypoint: python3 -c 'from language.text2speech.Txt2Mp3 import Txt2Mp3; from
      wsgiref import simple_server; simple_server.make_server("0.0.0.0", 7777, Txt2Mp3.application).serve_forever()'
    environment: {GDB_HOST: gdb, GDB_PASSWORD: '${GDB_PASSWORD}', INSIDE: 'true',
      LANG: en_US.UTF - 8, LANGUAGE: en_US.UTF-8, LC_ALL: en_US.UTF-8}
    image: full_python
    networks: [db]
    restart: unless-stopped
    volumes: [$CWD/python:/home/finn/Programming/self-reading-library/python, $CWD/.layouteagle/audio/:/home/finn/Programming/self-reading-library/python/.layouteagle/audio/language/text2speech/]
  train_elmodifferencetrain:
    build: python
    container_name: train_elmodifferencetrain
    entrypoint: python3 -c 'from language.transformer.ElmoDifferenceTrain import ElmoDifferenceTrain;  ElmoDifferenceTrain.wait_for_change()'
    environment: {GDB_HOST: gdb, GDB_PASSWORD: '${GDB_PASSWORD}', INSIDE: 'true',
      LANG: en_US.UTF - 8, LANGUAGE: en_US.UTF-8, LC_ALL: en_US.UTF-8}
    image: full_python
    networks: [db]
    restart: unless-stopped
    volumes: [$CWD/python:/home/finn/Programming/self-reading-library/python]
