version: "3"
services:

  db:
    image: nawer/blazegraph
    restart: unless-stopped
    environment:
      JAVA_XMS: 512m
      JAVA_XMX: 1g
    networks:
      - db
    volumes:
      - .layouteagle/blazegraph:/var/lib/blazegraph
    ports:
      - "12345:9999"

  inotify:
    image: debian
    restart: unless-stopped
    entrypoint:  bash inotify.sh  /home/finn/Programming/self-reading-library/python
    volumes:
      - "$CWD/inotify.sh:/inotify.sh"
      - "$CWD/python:/home/finn/Programming/self-reading-library/python"

networks:
  db:
    external: True



