version: "3"
services:

  gdb:
    image: franzinc/agraph
    container_name: gdb
    restart: unless-stopped
    shm_size: 3g
    environment:
      AGRAPH_SUPER_USER: ich
      AGRAPH_SUPER_PASSWORD: ${GDB_PASSWORD}
    networks:
      - db
    ports:
      - 10000-10035:10000-10035
    #volumes:
    #  - "$CWD/gdb/data:/agraph/data"
    #  - "$CWD/gdb/etc:/agraph/etc"



networks:
  db:
    external: True



