services:
  micro_layout2readingorder:
    build: python
    container_name: micro_layout2readingorder
    entrypoint: python3 -c 'from layout.Layout2ReadingOrder import Layout2ReadingOrder;
      from wsgiref import simple_server ; simple_server.make_server("0.0.0.0", 7777,
      Layout2ReadingOrder.application).serve_forever()'
    environment: {INSIDE: 'true', LANG: en_US.UTF - 8, LANGUAGE: en_US.UTF-8, LC_ALL: en_US.UTF-8}
    image: full_python
    ports: [7777:7777]
    volumes: [$CWD/python:/home/finn/Programming/self-reading-library/python]
