version: "3"
services:
  b:
    build: python
    container_name: be
    ports:
      - "3815:3000"
    tty: true
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  f:
    build: react
    container_name: fe
    ports:
      - "3210:3000"
    tty: true
    environment:
      PORT: 3000


