version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - be
      - fe
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./react/layout_viewer_made/.next/:/next/.next/
      - "$CWD/python/.layouteagle/pdfs/:/pdfs"
      - "$CWD/python/.layouteagle/audio/:/audio"
    networks:
      - world

  be:
    image: full_python
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

    build: python
    container_name: be

    tty: true
    user: $USER_IDS
    ports:
      - "${PORT}:${PORT}"
      - "9876:9999"
      - "2222:22"
    expose:
      - "2345"
    environment:
      PORT: $PORT
      DB: ${DOCKER_DB}
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

      DEBUG: "true"
    networks:
      - db
      - world
    extra_hosts:
        - "host.docker.internal:host-gateway"

    volumes:
      - "$CWD/python:/home/finn/Programming/self-reading-library/python"
    entrypoint:  bash entrypoint.be.sh

  fill:
    build: python
    container_name: fill
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - "2229:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "3456"
    tty: true
    networks:
      - db
    environment:
      DB: ${DB}
      DB_HOST: db
      GDB_PASSWORD: ${GDB_PASSWORD}
      GDB_HOST: gdb

    volumes:
      - "$CWD/python:/home/finn/Programming/self-reading-library/python"
    entrypoint:  bash entrypoint.fill.sh

  recompute:
    build: python
    container_name: recompute
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    tty: true
    ports:
      - "2223:22"
    networks:
      - db
    environment:
      DB: ${DB}
      DB_HOST: db
      GDB_PASSWORD: ${GDB_PASSWORD}
      GDB_HOST: gdb

    volumes:
      - "$CWD/python:/home/finn/Programming/self-reading-library/python"
    entrypoint:  bash entrypoint.recompute.sh




  fe:
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    build:
      context: react
      dockerfile: Dockerfile.${ENV}

      args:
        NEXT_PUBLIC_FRONTEND_HOST: ${FRONTEND_HOST}
        NEXT_PUBLIC_BACKEND_HOST: "/api"
        NEXT_PUBLIC_DASH_HOST: "/dash"
    container_name: fe
    ports:
      - "3210:3000"
    tty: true
    volumes:

      - "$CWD/react/layout_viewer_made/config:/app/config"
      - "$CWD/react/layout_viewer_made/public:/app/public"
      - "$CWD/react/layout_viewer_made/pages:/app/pages"
      - "$CWD/react/layout_viewer_made/spec:/app/spec"
      - "$CWD/react/layout_viewer_made/src:/app/src"

    environment:
      PORT: 3000
      NEXT_PUBLIC_FRONTEND_HOST: ${FRONTEND_HOST}
      NEXT_PUBLIC_BACKEND_HOST: "/api"
      NEXT_PUBLIC_DASH_HOST: "/dash"
    networks:
      - world

  inotify:
    container_name: inotify
    image: debian
    ports:
     - "2225:22"
    restart: unless-stopped
    entrypoint:  bash inotify.sh  /home/finn/Programming/self-reading-library/python
    volumes:
      - "$CWD/inotify.sh:/inotify.sh"
      - "$CWD/python:/home/finn/Programming/self-reading-library/python"


networks:
  db:
    external: True
  world:

