version: "3"
services:
  rest:
    build: python
    container_name: rest

    tty: true
    user: $USER_IDS
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: $PORT
      DB_HOST: db
    volumes:
      - "$CWD/python:/home/finn/Programming/self-reading-library/python"
    #  - "$CWD/python/.layouteagle:/home/finn/Programming/self-reading-library/python/.layouteagle"
    entrypoint: uwsgi  --py-autoreload=1 --http 0.0.0.0:$PORT --module wsgi:application --memory-report  --workers 16 --threads 2  --memory-report --enable-threads --skip-atexit-teardown --max-worker-lifetime=1000 --max-worker-lifetime-delta=2000 --harakiri=3000
    #entrypoint: gunicorn --bind 0.0.0.0:$PORT --log-level info -w 4 -k uvicorn.workers.UvicornWorker wsgi:application  --timeout 600
  fill:
    build: python
    container_name: fill
    tty: true
    environment:
      DB_HOST: db
    volumes:
      - "$CWD/python:/home/finn/Programming/self-reading-library/python"
    entrypoint: python3 fill.py

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: python
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: "localhost"
      CREATE_FRONTEND: True
  fe:
    build: react
    container_name: fe
    ports:
      - "3210:3000"
    tty: true
    volumes:
      - "$CWD/self-reading-library/python/.layouteagle/pdfs/:/home/finn/Programming/self-reading-library/react/layout_viewer_made/public/pdfs"
      - "$CWD/self-reading-library/python/.layouteagle/audio/:/home/finn/Programming/self-reading-library/react/layout_viewer_made/public/audio"
      - "$CWD/react/layout_viewer_made/src:/app/src"

    environment:
      PORT: 3000



