
name: Deploy to VM staging

on:
  push:
    branches:
      - master

permissions:
  contents: read


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}


      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
        run: |
          ssh staging "
              set -x
              killall screen
              rm -rf *.log
              rm -rf ./cache
              cp -R ./LayoutEagle/python/.layouteagle ./cache
              kill -9 $(lsof -t -i:9999) || echo 'backend not running'
              killall -9 uwsgi || echo 'backend not running'
              killall -9 python || echo 'backend not running'

              rm -rf LayoutEagle
              git clone https://github.com/c0ntradicti0n/LayoutEagle.git 
                        
              python3 -m venv venv
              . venv/bin/activate
          
              [[ ! -d ./models ]] && mkdir models && cd models && wget https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json && wget https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5 && cd ..
              ln -s /home/deploy/models/ /home/deploy/LayoutEagle/python/language/transformer/models

              cd LayoutEagle
          
              mkdir python/.layouteagle
              mkdir python/.layouteagle/pdfs || echo 'exists'

          
              tar -xf ~/arXiv_pdf_9912_002.tar -C python/.layouteagle/pdfs 

              cp -R --no-clobber ../minimal_cache/. python/.layouteagle/

              cp -R --no-clobber ~/cache/. python/.layouteagle/
              
              mkdir python/.layouteagle/cache || echo 'exists'
            

              mkdir python/.layouteagle/prediction
              ls python/.layouteagle/
          "

      - name: InstallTts
        run: |
            ssh staging '   
                cd LayoutEagle
                if [[ ! -d ./tts ]] ; then
                  git clone https://github.com/c0ntradicti0n/tts.git
                  cd tts 
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements.txt
                fi
            '
      - name: Build
        run: |
          ssh staging '   
              make build
          '
      - name: Build
        run: |
          ssh staging '   
              make down up
          '
      - name: RestTest
        run: |
          echo $(curl http://$SSH_HOST:80) 
          echo $(curl -k https://$SSH_HOST:9999)