
name: Deploy to VM staging

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Deploy
        run: |
          ssh staging '
              set -x
              rm -rf ./app
              rm -rf ./cache
              cp -r ./LayoutEagle/python/.layouteagle ./cache
              sudo rm -rf LayoutEagle
              git clone https://github.com/c0ntradicti0n/LayoutEagle.git 
          
              cp -r  ./cache ./LayoutEagle/python/.layouteagle
              mkdir LayoutEagle/python/.layouteagle/collection
              tar -xf  .layouteagle-box-data-collection.tar.xz -C LayoutEagle/python/.layouteagle/collection
              
              python3 -m venv venv
              . venv/bin/activate.fish 
              cd LayoutEagle

              pip install wheel
              pip install torch
              pip install -r ./python/requirements.txt
              pip install numpy --upgrade

          '

      - name: StartBack
        run: |
          ssh staging '            screen -L -S backend -dm bash -c " . venv/bin/activate.fish; cd LayoutEagle/python; python3 backend.py"    '
          
      - name: StartWeb
        run: |
          ssh staging 'sleep 300 ;  screen -S frontend -dm bash -c " cd LayoutEagle/react/layout_viewer_made/ ; yarn install; yarn add --dev typescript @types/node; yarn run build ; sudo yarn run start -p 80 "     '

      - name: DocTest
        run: |
          ssh staging '        
              screen -S fullend -dm bash -c "cd fullend/LayoutEagle/python; pip install -U pytest; pytest --doctest-modules"
          '
      - name: RestTest
        run: |
          echo $(curl http://$SSH_HOST:80) 
          echo $(curl -k https://$SSH_HOST:443)